services:
  - type: web
    name: mkite-kitchen
    env: node
    plan: free
    buildCommand: |
      # Move to the production directory
      npm install
      # Build client and server
      npm run build
      # Create the public directory
      mkdir -p server/public
      # Copy the client build to the server's static directory
      cp -r client/dist/* server/public/
    startCommand: |
      NODE_ENV=production npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mkite-kitchen-db
          property: connectionString

databases:
  - name: mkite-kitchen-db
    plan: free