services:
  - type: web
    name: mkite-kitchen
    env: node
    plan: free
    buildCommand: bash build.sh
    startCommand: bash run.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mkite-kitchen-db
          property: connectionString

databases:
  - name: mkite-kitchen-db
    plan: free